//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSCProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Expense
    {
        public int Id { get; set; }
        public string Description { get; set; }
        public int Price { get; set; }
        public System.DateTime Date { get; set; }
        public int EmployeeId { get; set; }
        public bool Deleted { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
