//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSCProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inventory
    {
        public string LotId { get; set; }
        public int ItemId { get; set; }
        public int WarehouseId { get; set; }
        public float Quantity { get; set; }
        public bool Deleted { get; set; }
    
        public virtual Part Part { get; set; }
        public virtual Lot Lot { get; set; }
        public virtual Warehouse Warehouse { get; set; }
    }
}
