//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSCProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseOrderPart
    {
        public int OrderId { get; set; }
        public int PartId { get; set; }
        public float Quantity { get; set; }
        public bool Deleted { get; set; }
    
        public virtual PurchaseOrder PurchaseOrder { get; set; }
        public virtual Part Part { get; set; }
    }
}
